import type { Metadata } from "next";
import "./globals.css";
import FlashingImage from "@/components/FlashingImage"; // Assuming @ maps to src/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="antialiased">
        {children}
        <FlashingImage />
      </body>
    </html>
  );
}
